"""Seed the Cairn MongoDB with users, DBA runbooks, and execution history.

Idempotent by construction: every document gets a deterministic ``_id`` derived
from a natural key (user email, runbook slug, execution index) via ``det_oid``.
Re-running ``replace_one(..., upsert=True)`` therefore overwrites documents in
place instead of creating duplicates, and cross-references (``owner_id``,
``related_runbook_ids``) resolve to those same deterministic ids.

Run:  python -m scripts.seed_mongo
(Requires MONGO_URI to point at a reachable MongoDB, e.g.
 mongodb://localhost:27017/cairn)
"""

from __future__ import annotations

import hashlib
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

# Allow running as a plain file (python scripts/seed_mongo.py) as well as a
# module (python -m scripts.seed_mongo) by ensuring the project root is on the
# import path before importing the app package.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from bson import ObjectId, json_util  # noqa: E402
from pymongo import ASCENDING  # noqa: E402

from app.db.mongo import get_mongo  # noqa: E402

# Fixed epoch so created_at/updated_at/ran_at are stable across runs.
BASE = datetime(2026, 1, 1, tzinfo=timezone.utc)


def det_oid(*parts: str) -> ObjectId:
    """Deterministic ObjectId from a natural key, keeping seeding idempotent."""
    digest = hashlib.md5("::".join(parts).encode()).hexdigest()
    return ObjectId(digest[:24])


def build_steps(raw: list[tuple[str, str | None, str | None]]) -> list[dict]:
    """Turn (instruction, command, expected_result) tuples into ordered steps."""
    return [
        {
            "order": i,
            "instruction": instruction,
            "command": command,
            "expected_result": expected_result,
        }
        for i, (instruction, command, expected_result) in enumerate(raw, start=1)
    ]


USERS = [
    {"name": "Ana Ruiz", "email": "ana.ruiz@example.com", "team": "Database Reliability"},
    {"name": "Marcus Chen", "email": "marcus.chen@example.com", "team": "Platform SRE"},
    {"name": "Priya Nair", "email": "priya.nair@example.com", "team": "Database Reliability"},
    {"name": "Tom O'Brien", "email": "tom.obrien@example.com", "team": "Storage & Data"},
    {"name": "Yuki Tanaka", "email": "yuki.tanaka@example.com", "team": "Platform SRE"},
]


RUNBOOKS = [
    # ---------------------------------------------------------------- PostgreSQL
    {
        "slug": "pg-recover-replica-wal-lag",
        "title": "Recover a PostgreSQL replica from WAL lag",
        "category": "postgresql",
        "severity": "incident",
        "summary": "A streaming standby has fallen behind the primary; diagnose whether it is receive- or replay-bound and drain the lag, re-seeding if the replication slot was lost.",
        "owner": "ana.ruiz@example.com",
        "tags": ["postgresql", "replication", "wal", "standby", "incident"],
        "related": ["pg-promote-standby-failover"],
        "steps": [
            ("Confirm replication lag on the standby.",
             'psql -Atc "SELECT now() - pg_last_xact_replay_timestamp() AS replay_lag;"',
             "replay_lag is minutes or hours, confirming the standby is behind."),
            ("Check that the primary still retains the WAL this standby needs.",
             'psql -h primary -Atc "SELECT slot_name, active, wal_status, restart_lsn FROM pg_replication_slots;"',
             "wal_status is 'reserved'; a value of 'lost' means the slot can no longer feed this standby."),
            ("Determine whether lag is receive-bound or replay-bound.",
             'psql -Atc "SELECT pg_last_wal_receive_lsn(), pg_last_wal_replay_lsn();"',
             "Receive LSN advances while replay LSN trails, so replay (not the network) is the bottleneck."),
            ("Look for a recovery conflict stalling the startup process.",
             "psql -Atc \"SELECT wait_event_type, wait_event, state FROM pg_stat_activity WHERE backend_type='startup';\"",
             "A Recovery* wait event indicates a replay conflict or slow I/O."),
            ("Check disk utilization on the standby data volume.",
             "iostat -x 5 3",
             "%util near 100% confirms the replay is I/O bound."),
            ("If the slot is lost, re-seed the standby from the primary.",
             "pg_basebackup -h primary -D /var/lib/postgresql/16/main -U replicator -R -X stream -c fast -P",
             "A fresh base backup completes and writes standby.signal and primary_conninfo."),
            ("Start the standby and confirm it resumes streaming.",
             "sudo systemctl start postgresql@16-main",
             "Logs show 'started streaming WAL from primary'."),
            ("Watch the lag drain toward a steady state.",
             "watch -n5 'psql -Atc \"SELECT now() - pg_last_xact_replay_timestamp();\"'",
             "replay_lag falls steadily toward a few seconds."),
        ],
    },
    {
        "slug": "pg-terminate-blocking-queries",
        "title": "Diagnose and terminate blocking queries in PostgreSQL",
        "category": "postgresql",
        "severity": "incident",
        "summary": "Application queries are stuck behind a lock. Walk the wait chain, find the root blocker, cancel or terminate it, and add a lock_timeout to prevent recurrence.",
        "owner": "marcus.chen@example.com",
        "tags": ["postgresql", "locks", "blocking", "performance", "incident"],
        "related": ["pg-recover-replica-wal-lag", "pg-repack-table-bloat"],
        "steps": [
            ("Identify blocked sessions and the PIDs blocking them.",
             'psql -Atc "SELECT pid, pg_blocking_pids(pid) AS blocked_by, state, wait_event, left(query,60) FROM pg_stat_activity WHERE cardinality(pg_blocking_pids(pid)) > 0;"',
             "Rows list each blocked PID and the PID(s) holding the conflicting lock."),
            ("Inspect the ungranted locks to find the contended object.",
             'psql -Atc "SELECT locktype, relation::regclass, mode, granted, pid FROM pg_locks WHERE NOT granted;"',
             "Ungranted lock rows point at the contended relation and lock mode."),
            ("Find the oldest offending transaction at the head of the chain.",
             "psql -Atc \"SELECT pid, now()-xact_start AS age, left(query,80) FROM pg_stat_activity WHERE state <> 'idle' ORDER BY xact_start LIMIT 5;\"",
             "The transaction with the largest age is the root blocker."),
            ("Check whether the blocker is idle in transaction.",
             "psql -Atc \"SELECT pid, state, now()-state_change AS idle_for FROM pg_stat_activity WHERE state='idle in transaction' ORDER BY idle_for DESC;\"",
             "A long idle_for means an application left a transaction open."),
            ("Cancel the blocking statement first (non-destructive).",
             'psql -Atc "SELECT pg_cancel_backend(<blocker_pid>);"',
             "Returns t; the blocker's statement is cancelled without dropping the connection."),
            ("If cancel is ignored, terminate the backend.",
             'psql -Atc "SELECT pg_terminate_backend(<blocker_pid>);"',
             "Returns t; the session is killed and waiting queries proceed."),
            ("Confirm the wait chain has cleared.",
             'psql -Atc "SELECT count(*) FROM pg_stat_activity WHERE cardinality(pg_blocking_pids(pid)) > 0;"',
             "Count returns 0."),
            ("Set a lock_timeout on the app role to prevent recurrence.",
             "psql -c \"ALTER ROLE app SET lock_timeout = '5s';\"",
             "Future statements that wait too long for a lock fail fast instead of piling up."),
        ],
    },
    {
        "slug": "pg-repack-table-bloat",
        "title": "Reclaim PostgreSQL table bloat with pg_repack",
        "category": "postgresql",
        "severity": "maintenance",
        "summary": "A hot table has accumulated dead tuples and disk bloat. Measure it, repack it online without a long exclusive lock, and tune autovacuum to keep it from returning.",
        "owner": "priya.nair@example.com",
        "tags": ["postgresql", "bloat", "vacuum", "pg_repack", "maintenance"],
        "related": ["pg-terminate-blocking-queries"],
        "steps": [
            ("Measure size and dead tuples on the suspect table.",
             "psql -Atc \"SELECT pg_size_pretty(pg_total_relation_size('orders')) AS total, n_dead_tup, n_live_tup FROM pg_stat_user_tables WHERE relname='orders';\"",
             "A high dead-tuple ratio and large total size confirm bloat."),
            ("Check the last autovacuum and analyze times.",
             "psql -Atc \"SELECT last_autovacuum, last_autoanalyze FROM pg_stat_user_tables WHERE relname='orders';\"",
             "A stale or null last_autovacuum suggests autovacuum is falling behind."),
            ("Ensure the pg_repack extension is installed.",
             'psql -c "CREATE EXTENSION IF NOT EXISTS pg_repack;"',
             "Extension installs without error."),
            ("Confirm enough free disk (repack builds a full copy).",
             "df -h /var/lib/postgresql",
             "Free space exceeds the table's total size."),
            ("Repack the table online (brief exclusive lock only at swap).",
             "pg_repack -d cairn -t orders --jobs 2",
             "Repack completes with 'INFO: repacking table' and no long global lock."),
            ("Re-measure size and dead tuples.",
             "psql -Atc \"SELECT pg_size_pretty(pg_total_relation_size('orders')), n_dead_tup FROM pg_stat_user_tables WHERE relname='orders';\"",
             "Total size drops sharply and dead tuples reset near 0."),
            ("Tune autovacuum on the table to prevent re-bloat.",
             'psql -c "ALTER TABLE orders SET (autovacuum_vacuum_scale_factor=0.02, autovacuum_vacuum_cost_limit=2000);"',
             "Autovacuum now triggers earlier and runs faster on this hot table."),
        ],
    },
    {
        "slug": "pg-promote-standby-failover",
        "title": "Promote a PostgreSQL standby during primary failover",
        "category": "postgresql",
        "severity": "incident",
        "summary": "The primary is down. Pick the most caught-up standby, fence the old primary to avoid split-brain, promote, repoint replicas and traffic, then rebuild the old node with pg_rewind.",
        "owner": "ana.ruiz@example.com",
        "tags": ["postgresql", "failover", "promotion", "ha", "incident"],
        "related": ["pg-recover-replica-wal-lag"],
        "steps": [
            ("Confirm the primary is truly down, not a network blip.",
             "pg_isready -h primary -t 5",
             "Returns 'no response'; retry from a second network path to rule out a partition."),
            ("Pick the most caught-up standby by replay LSN.",
             'psql -h standby1 -Atc "SELECT pg_last_wal_replay_lsn();"',
             "Compare LSNs across standbys; the highest has the least data loss."),
            ("Fence the old primary to prevent split-brain.",
             "ssh primary 'sudo systemctl stop postgresql@16-main' || echo 'unreachable - ensure it stays down'",
             "Old primary is stopped or confirmed unreachable."),
            ("Promote the chosen standby.",
             "ssh standby1 'sudo -u postgres pg_ctl promote -D /var/lib/postgresql/16/main'",
             "Log shows 'database system is ready to accept connections'."),
            ("Verify it is now read-write.",
             'psql -h standby1 -Atc "SELECT pg_is_in_recovery();"',
             "Returns f (no longer in recovery)."),
            ("Repoint the remaining standbys at the new primary.",
             "psql -h standby2 -c \"ALTER SYSTEM SET primary_conninfo = 'host=standby1 user=replicator'\" && ssh standby2 'sudo systemctl restart postgresql@16-main'",
             "standby2 reconnects and streams from the new primary."),
            ("Move the application/VIP to the new primary.",
             'kubectl -n app patch svc pg-primary -p \'{"spec":{"selector":{"role":"primary-standby1"}}}\'',
             "Application connections land on the promoted node."),
            ("Rebuild the old primary as a standby once recovered.",
             "pg_rewind --target-pgdata=/var/lib/postgresql/16/main --source-server='host=standby1 user=replicator'",
             "pg_rewind syncs divergent blocks so the old primary can rejoin as a standby."),
        ],
    },
    {
        "slug": "pg-rotate-passwords",
        "title": "Rotate PostgreSQL role passwords without downtime",
        "category": "postgresql",
        "severity": "routine",
        "summary": "Scheduled credential rotation: generate a SCRAM password with an expiry, store it in the vault, roll it to the app, and confirm no clients still use the old secret.",
        "owner": "tom.obrien@example.com",
        "tags": ["postgresql", "security", "credentials", "rotation", "routine"],
        "related": [],
        "steps": [
            ("List login roles ordered by expiry to find those due.",
             'psql -Atc "SELECT rolname, rolvaliduntil FROM pg_roles WHERE rolcanlogin ORDER BY rolvaliduntil NULLS FIRST;"',
             "Roles with a past or near valid-until date are due for rotation."),
            ("Generate a strong random password.",
             "openssl rand -base64 24",
             "A 32-character random secret is produced."),
            ("Set the new password with SCRAM and an expiry.",
             "psql -c \"SET password_encryption='scram-sha-256'; ALTER ROLE app PASSWORD 'NEWSECRET' VALID UNTIL '2026-10-01';\"",
             "Role updated; \\du shows the new valid-until."),
            ("Store the secret in the vault.",
             "vault kv put secret/cairn/pg/app password='NEWSECRET'",
             "Vault returns a new version number."),
            ("Roll the secret to the app without a restart.",
             "kubectl -n app rollout restart deploy/api",
             "Pods pick up the new secret via their projected volume."),
            ("Verify the app authenticates with the new password.",
             "PGPASSWORD='NEWSECRET' psql -h primary -U app -Atc 'SELECT 1;'",
             "Returns 1."),
            ("Confirm no clients still use the old credential.",
             "psql -Atc \"SELECT usename, client_addr, count(*) FROM pg_stat_activity WHERE usename='app' GROUP BY 1,2;\"",
             "All active app sessions were established after the rollout."),
        ],
    },
    # ------------------------------------------------------------------- MongoDB
    {
        "slug": "mongo-rotate-replica-member",
        "title": "Rotate a MongoDB replica-set member",
        "category": "mongodb",
        "severity": "maintenance",
        "summary": "Replace an aging replica-set node with a fresh one via a rolling change: verify quorum tolerance, remove the old member, add the replacement, and let initial sync catch it up.",
        "owner": "priya.nair@example.com",
        "tags": ["mongodb", "replica-set", "rolling", "maintenance"],
        "related": ["mongo-resync-stale-secondary"],
        "steps": [
            ("Check replica-set health and identify the member to replace.",
             "mongosh --quiet --eval 'rs.status().members.forEach(m=>print(m.name,m.stateStr,m.health))'",
             "All members report health 1; note the SECONDARY to rotate."),
            ("Ensure the set tolerates losing one member (majority stays up).",
             "mongosh --quiet --eval 'rs.status().members.filter(m=>m.stateStr==\"PRIMARY\"||m.stateStr==\"SECONDARY\").length'",
             "At least 2 healthy voting members remain after removal."),
            ("Remove the old member from the config.",
             "mongosh --eval 'rs.remove(\"old-node:27017\")'",
             "Reconfig returns { ok: 1 } and the member disappears from rs.status()."),
            ("Start mongod on the replacement with the same keyFile and replSet.",
             "mongod --config /etc/mongod.conf --replSet rs0 --fork",
             "mongod starts and logs 'waiting for connections'."),
            ("Add the new member so initial sync begins.",
             "mongosh --eval 'rs.add(\"new-node:27017\")'",
             "Member appears as STARTUP2 and begins initial sync."),
            ("Watch the new member's state progress.",
             "mongosh --quiet --eval 'rs.status().members.find(m=>m.name==\"new-node:27017\").stateStr'",
             "State transitions STARTUP2 -> RECOVERING -> SECONDARY."),
            ("Verify oplog replication lag is near zero.",
             "mongosh --quiet --eval 'rs.printSecondaryReplicationInfo()'",
             "The new member reports only a few seconds behind the primary."),
            ("Re-check priorities and votes match the intended topology.",
             "mongosh --eval 'cfg=rs.conf(); printjson(cfg.members.map(m=>({h:m.host,p:m.priority,v:m.votes})))'",
             "Priorities and votes are as designed."),
        ],
    },
    {
        "slug": "mongo-recover-election-storm",
        "title": "Recover a MongoDB replica set from an election storm",
        "category": "mongodb",
        "severity": "incident",
        "summary": "The set has no stable primary and keeps re-electing. Rule out partitions and clock skew, damp the flapping member, force a healthy primary if quorum is lost, then restore topology.",
        "owner": "marcus.chen@example.com",
        "tags": ["mongodb", "elections", "replica-set", "availability", "incident"],
        "related": ["mongo-rotate-replica-member", "mongo-resync-stale-secondary"],
        "steps": [
            ("Confirm there is no stable primary.",
             "mongosh --quiet --eval 'rs.status().members.map(m=>m.stateStr).join(\",\")'",
             "States flap between PRIMARY/SECONDARY or show no PRIMARY."),
            ("Check reachability between members for a partition.",
             "for h in node1 node2 node3; do mongosh --host $h --quiet --eval 'rs.status().ok' ; done",
             "A member that cannot see the others points at a partition."),
            ("Look for election churn in the logs.",
             "grep -E 'election|stepdown|not enough votes' /var/log/mongodb/mongod.log | tail -20",
             "Repeated election attempts confirm an election storm."),
            ("Check for clock skew across members.",
             "for h in node1 node2 node3; do ssh $h 'date -u +%s'; done",
             "Timestamps agree within ~1s; large skew destabilizes elections."),
            ("Damp the flapping member so it cannot win elections.",
             "mongosh --eval 'cfg=rs.conf(); cfg.members.find(m=>m.host==\"flaky:27017\").priority=0; rs.reconfig(cfg)'",
             "The unstable node can no longer become primary, calming elections."),
            ("If quorum is lost, force a healthy member to primary.",
             "mongosh --host good-node --eval 'rs.reconfig(rs.conf(), {force:true})'",
             "The healthy member establishes a stable PRIMARY."),
            ("Confirm a single stable primary.",
             "mongosh --quiet --eval 'rs.isMaster().primary'",
             "The same primary is reported consistently across repeated calls."),
            ("Restore original priorities once stable.",
             "mongosh --eval 'cfg=rs.conf(); cfg.members.find(m=>m.host==\"flaky:27017\").priority=1; rs.reconfig(cfg)'",
             "Topology returns to its intended configuration."),
        ],
    },
    {
        "slug": "mongo-resync-stale-secondary",
        "title": "Resync a stale MongoDB secondary from scratch",
        "category": "mongodb",
        "severity": "incident",
        "summary": "A secondary fell off the oplog and is stuck in RECOVERING. Wipe its data directory to force a full initial sync, then widen the oplog so it does not recur.",
        "owner": "priya.nair@example.com",
        "tags": ["mongodb", "initial-sync", "oplog", "replication", "incident"],
        "related": ["mongo-rotate-replica-member"],
        "steps": [
            ("Confirm the secondary is stale (stuck in RECOVERING).",
             "mongosh --host stale-node --quiet --eval 'rs.status().members.find(m=>m.self).stateStr'",
             "State is RECOVERING and not advancing, indicating it fell off the oplog."),
            ("Check the primary's oplog window.",
             "mongosh --host primary --quiet --eval 'rs.printReplicationInfo()'",
             "The oplog only covers a few hours; the secondary was down longer."),
            ("Stop mongod on the stale member.",
             "ssh stale-node 'sudo systemctl stop mongod'",
             "Process stops cleanly."),
            ("Clear the data directory to force a full resync.",
             "ssh stale-node 'sudo rm -rf /var/lib/mongodb/* && sudo -u mongodb mkdir -p /var/lib/mongodb'",
             "Data path is empty and owned by the mongodb user."),
            ("Start mongod to trigger initial sync.",
             "ssh stale-node 'sudo systemctl start mongod'",
             "Member rejoins as STARTUP2 and begins copying data."),
            ("Monitor the initial sync progress.",
             "mongosh --host stale-node --quiet --eval 'db.serverStatus().initialSync'",
             "Progress fields advance through data copy and oplog application."),
            ("Confirm it reaches SECONDARY and catches up.",
             "mongosh --host stale-node --quiet --eval 'rs.status().members.find(m=>m.self).stateStr'",
             "State becomes SECONDARY with minimal replication lag."),
            ("Grow the oplog to widen the recovery window.",
             "mongosh --host primary --eval 'db.adminCommand({replSetResizeOplog:1, size: 20480})'",
             "Oplog max size increases to 20 GB."),
        ],
    },
    {
        "slug": "mongo-add-shard",
        "title": "Add a shard to a MongoDB sharded cluster",
        "category": "mongodb",
        "severity": "maintenance",
        "summary": "Scale a sharded cluster horizontally: stand up a new shard replica set, register it via mongos, and let the balancer migrate chunks within a maintenance window.",
        "owner": "tom.obrien@example.com",
        "tags": ["mongodb", "sharding", "scaling", "balancer", "maintenance"],
        "related": ["mongo-compact-collection"],
        "steps": [
            ("Confirm the cluster is sharded and healthy.",
             "mongosh --host mongos --quiet --eval 'sh.status()'",
             "sh.status() lists existing shards and the config servers are reachable."),
            ("Initiate the new shard as its own replica set.",
             "mongosh --host newshard-node1 --eval 'rs.initiate({_id:\"shardC\",members:[{_id:0,host:\"newshard-node1:27018\"},{_id:1,host:\"newshard-node2:27018\"},{_id:2,host:\"newshard-node3:27018\"}]})'",
             "New replica set shardC elects a primary."),
            ("Register the shard with the cluster via mongos.",
             "mongosh --host mongos --eval 'sh.addShard(\"shardC/newshard-node1:27018,newshard-node2:27018\")'",
             "Returns { shardAdded: 'shardC', ok: 1 }."),
            ("Verify the balancer is enabled.",
             "mongosh --host mongos --quiet --eval 'sh.getBalancerState()'",
             "Returns true; chunks will migrate onto the new shard."),
            ("Watch chunk distribution rebalance.",
             "mongosh --host mongos --quiet --eval 'db.getSiblingDB(\"config\").chunks.aggregate([{$group:{_id:\"$shard\",n:{$sum:1}}}]).toArray()'",
             "Chunk counts on existing shards drop as shardC's count rises."),
            ("Constrain balancing to a maintenance window.",
             "mongosh --host mongos --eval 'db.getSiblingDB(\"config\").settings.updateOne({_id:\"balancer\"},{$set:{activeWindow:{start:\"01:00\",stop:\"05:00\"}}},{upsert:true})'",
             "The balancer only migrates chunks during the defined window."),
            ("Confirm the new shard serves data.",
             "mongosh --host mongos --quiet --eval 'db.getSiblingDB(\"app\").events.getShardDistribution()'",
             "Distribution shows data resident on shardC."),
        ],
    },
    {
        "slug": "mongo-compact-collection",
        "title": "Compact a MongoDB collection to reclaim disk",
        "category": "mongodb",
        "severity": "routine",
        "summary": "Reclaim WiredTiger free space rolling through the set: compact secondaries first, then step down and compact the former primary, verifying disk is returned to the OS.",
        "owner": "yuki.tanaka@example.com",
        "tags": ["mongodb", "compaction", "wiredtiger", "disk", "routine"],
        "related": [],
        "steps": [
            ("Identify reclaimable space in the collection.",
             "mongosh --quiet --eval 'db.events.stats().wiredTiger[\"block-manager\"][\"file bytes available for reuse\"]'",
             "A large 'bytes available for reuse' indicates reclaimable space."),
            ("Compact on a secondary first to spare the primary.",
             "mongosh --host secondary --eval 'db.runCommand({compact:\"events\"})'",
             "Returns { ok: 1 } and the on-disk file shrinks."),
            ("Verify the secondary stayed in the set.",
             "mongosh --host secondary --quiet --eval 'rs.status().members.find(m=>m.self).stateStr'",
             "Remains SECONDARY (compact blocks reads on that node but not the set)."),
            ("Step down the primary before compacting it.",
             "mongosh --host primary --eval 'rs.stepDown(120)'",
             "A secondary is elected primary."),
            ("Compact the stepped-down node.",
             "mongosh --host old-primary --eval 'db.runCommand({compact:\"events\"})'",
             "Returns { ok: 1 }."),
            ("Confirm disk was reclaimed at the OS level.",
             "df -h /var/lib/mongodb",
             "Used space on the data volume drops."),
        ],
    },
    # --------------------------------------------------------------------- MySQL
    {
        "slug": "mysql-reclaim-table-bloat",
        "title": "Reclaim space after MySQL table bloat",
        "category": "mysql",
        "severity": "maintenance",
        "summary": "An InnoDB table holds large data_free after heavy deletes. Rebuild it online (pt-online-schema-change or in-place ALTER) to return space to the filesystem, then re-analyze.",
        "owner": "tom.obrien@example.com",
        "tags": ["mysql", "innodb", "bloat", "disk", "maintenance"],
        "related": ["mysql-online-schema-change-ghost"],
        "steps": [
            ("Find tables with the most reclaimable free space.",
             "mysql -e \"SELECT table_name, ROUND(data_length/1048576) AS data_mb, ROUND(data_free/1048576) AS free_mb FROM information_schema.tables WHERE table_schema='app' ORDER BY data_free DESC LIMIT 10;\"",
             "Tables with large data_free hold reclaimable space from deletes/updates."),
            ("Confirm file-per-table so space returns to the OS.",
             "mysql -e \"SHOW VARIABLES LIKE 'innodb_file_per_table';\"",
             "Value is ON; otherwise space stays in the shared tablespace."),
            ("Check free disk (rebuild needs ~table size free).",
             "df -h /var/lib/mysql",
             "Free space exceeds the target table's size."),
            ("Rebuild online to avoid locking writes.",
             "pt-online-schema-change --alter 'ENGINE=InnoDB' D=app,t=orders --execute",
             "Tool builds a shadow table, backfills, and swaps with a brief metadata lock."),
            ("Alternatively, rebuild in place when supported.",
             'mysql -e "ALTER TABLE app.orders ENGINE=InnoDB, ALGORITHM=INPLACE, LOCK=NONE;"',
             "Rebuild completes without blocking DML."),
            ("Re-check reclaimed space.",
             "mysql -e \"SELECT ROUND(data_free/1048576) AS free_mb FROM information_schema.tables WHERE table_schema='app' AND table_name='orders';\"",
             "data_free drops sharply and the .ibd file shrinks on disk."),
            ("Refresh optimizer statistics after the rebuild.",
             'mysql -e "ANALYZE TABLE app.orders;"',
             "Status returns OK; statistics are up to date."),
        ],
    },
    {
        "slug": "mysql-recover-replication-gtid",
        "title": "Recover MySQL GTID replication after an apply error",
        "category": "mysql",
        "severity": "incident",
        "summary": "The replica SQL thread stopped on a duplicate-key or missing-row error. Confirm the data is already consistent, skip the single offending GTID with an empty transaction, and resume.",
        "owner": "marcus.chen@example.com",
        "tags": ["mysql", "replication", "gtid", "incident"],
        "related": ["mysql-rotate-binary-logs"],
        "steps": [
            ("Check replica status and the failing error.",
             "mysql -e 'SHOW REPLICA STATUS\\G' | grep -E 'Last_SQL_Error|Executed_Gtid|Replica_SQL_Running'",
             "Replica_SQL_Running is No with a duplicate-key or missing-row error."),
            ("Identify the GTID of the offending transaction.",
             "mysql -e 'SHOW REPLICA STATUS\\G' | grep Retrieved_Gtid_Set",
             "The transaction after Executed_Gtid_Set is the one failing to apply."),
            ("Decode the event on the source to see the conflicting row.",
             "mysqlbinlog --include-gtids='<uuid>:<n>' --base64-output=DECODE-ROWS -v /var/lib/mysql/binlog.000123",
             "The decoded row event shows exactly which row conflicts."),
            ("Verify the data is already in the intended post-state.",
             'mysql -e "SELECT * FROM app.orders WHERE id=<conflicting_id>\\G"',
             "The row already matches the target state, so the event is safe to skip."),
            ("Skip the single GTID with an empty transaction.",
             "mysql -e \"STOP REPLICA; SET GTID_NEXT='<uuid>:<n>'; BEGIN; COMMIT; SET GTID_NEXT='AUTOMATIC'; START REPLICA;\"",
             "The GTID is marked applied and the SQL thread advances past it."),
            ("Confirm replication resumes.",
             "mysql -e 'SHOW REPLICA STATUS\\G' | grep -E 'Replica_SQL_Running|Seconds_Behind_Source'",
             "Replica_SQL_Running is Yes and Seconds_Behind_Source starts decreasing."),
            ("If many rows diverged, checksum instead of skipping.",
             "pt-table-checksum --replicate=percona.checksums h=source,D=app,t=orders",
             "Any DIFFS must be reconciled with pt-table-sync rather than skipped."),
        ],
    },
    {
        "slug": "mysql-resolve-innodb-deadlocks",
        "title": "Diagnose and resolve recurring InnoDB deadlocks",
        "category": "mysql",
        "severity": "incident",
        "summary": "Transactions are deadlocking under load. Capture the latest deadlock, identify the lock order and index involved, and reduce lock scope with a better index and shorter transactions.",
        "owner": "priya.nair@example.com",
        "tags": ["mysql", "innodb", "deadlock", "locks", "incident"],
        "related": [],
        "steps": [
            ("Capture the most recent deadlock.",
             "mysql -e 'SHOW ENGINE INNODB STATUS\\G' | sed -n '/LATEST DETECTED DEADLOCK/,/WE ROLL BACK/p'",
             "The section shows the two transactions and the locks each held and wanted."),
            ("Enable persistent deadlock logging.",
             'mysql -e "SET GLOBAL innodb_print_all_deadlocks=ON;"',
             "Future deadlocks are written to the error log for later analysis."),
            ("Identify the statements and index involved.",
             "mysql -e 'SHOW ENGINE INNODB STATUS\\G' | grep -E 'index .* of table|WAITING FOR THIS LOCK|HOLDS THE LOCK'",
             "The contended index and lock access order are visible."),
            ("Inspect the locking plan of the offending query.",
             'mysql -e "EXPLAIN SELECT id FROM app.orders WHERE status=1 FOR UPDATE;"',
             "Gap/next-key locks on a secondary index reveal why two orders collide."),
            ("Add a covering index to reduce locked rows.",
             'mysql -e "ALTER TABLE app.orders ADD INDEX idx_status_created (status, created_at);"',
             "The query locks fewer rows, shrinking the deadlock window."),
            ("Shorten lock waits so the loser retries quickly.",
             'mysql -e "SET GLOBAL innodb_lock_wait_timeout=10;"',
             "Long lock waits fail fast and the app can retry the losing transaction."),
            ("Confirm deadlock frequency drops.",
             "mysql -e \"SHOW GLOBAL STATUS LIKE 'Innodb_deadlocks';\" ; sleep 300 ; mysql -e \"SHOW GLOBAL STATUS LIKE 'Innodb_deadlocks';\"",
             "The counter increments far more slowly than before."),
        ],
    },
    {
        "slug": "mysql-online-schema-change-ghost",
        "title": "Perform an online MySQL schema change with gh-ost",
        "category": "mysql",
        "severity": "maintenance",
        "summary": "Add a column to a large hot table with zero write downtime using gh-ost: dry-run, run against a replica tailing the binlog, throttle under load, and cut over atomically.",
        "owner": "tom.obrien@example.com",
        "tags": ["mysql", "schema-change", "gh-ost", "ddl", "maintenance"],
        "related": ["mysql-reclaim-table-bloat"],
        "steps": [
            ("Size the table to plan throttling and duration.",
             "mysql -e \"SELECT table_rows, ROUND(data_length/1048576) AS data_mb FROM information_schema.tables WHERE table_schema='app' AND table_name='orders';\"",
             "Row count and size inform throttling and expected runtime."),
            ("Dry-run the migration (no cutover).",
             "gh-ost --host=replica --database=app --table=orders --alter='ADD COLUMN fulfilled_at DATETIME NULL' --chunk-size=1000 --max-load=Threads_running=25 --initially-drop-ghost-table",
             "gh-ost validates connectivity and prints the plan without swapping."),
            ("Run for real, postponing cut-over behind a flag file.",
             "gh-ost --host=replica --database=app --table=orders --alter='ADD COLUMN fulfilled_at DATETIME NULL' --execute --postpone-cut-over-flag-file=/tmp/ghost.postpone",
             "A _orders_gho shadow table is created and backfills while tailing the binlog."),
            ("Monitor copy progress and replica lag.",
             "tail -f /var/log/ghost/orders.log | grep -E 'Copy:|Lag:'",
             "Copy percentage climbs and Lag stays under the configured threshold."),
            ("Throttle if production load rises.",
             "touch /tmp/ghost.throttle",
             "gh-ost pauses row copy while the throttle flag is present."),
            ("Trigger the atomic cut-over when ready.",
             "rm -f /tmp/ghost.postpone",
             "gh-ost swaps _orders_gho into place with a sub-second metadata lock."),
            ("Verify the new schema landed.",
             "mysql -e 'SHOW CREATE TABLE app.orders\\G'",
             "The fulfilled_at column is present; the _orders_del table can be dropped later."),
        ],
    },
    {
        "slug": "mysql-rotate-binary-logs",
        "title": "Rotate and purge MySQL binary logs to reclaim disk",
        "category": "mysql",
        "severity": "routine",
        "summary": "Binary logs are filling the data volume. Confirm replicas have consumed them, rotate to a fresh log, and purge old logs safely without breaking replication.",
        "owner": "yuki.tanaka@example.com",
        "tags": ["mysql", "binlog", "disk", "replication", "routine"],
        "related": ["mysql-recover-replication-gtid"],
        "steps": [
            ("Check current binary logs and disk usage.",
             "mysql -e 'SHOW BINARY LOGS;' ; df -h /var/lib/mysql",
             "Total binlog size and free disk are visible."),
            ("Confirm replicas have consumed the logs before purging.",
             "mysql -h replica -e \"SELECT * FROM performance_schema.replication_connection_status\\G\"",
             "Replicas' received GTID sets cover the logs you intend to purge."),
            ("Verify the configured retention.",
             "mysql -e \"SHOW VARIABLES LIKE 'binlog_expire_logs_seconds';\"",
             "Value reflects the intended retention (e.g. 604800 for 7 days)."),
            ("Rotate to a fresh binary log.",
             "mysql -e 'FLUSH BINARY LOGS;'",
             "A new binlog file is started and the previous one is closed."),
            ("Purge logs older than a safe point.",
             'mysql -e "PURGE BINARY LOGS BEFORE DATE_SUB(NOW(), INTERVAL 3 DAY);"',
             "Old binlog files are deleted and disk is freed."),
            ("Confirm disk freed and replicas still healthy.",
             "df -h /var/lib/mysql ; mysql -h replica -e 'SHOW REPLICA STATUS\\G' | grep Seconds_Behind_Source",
             "Free space rises and replicas report Seconds_Behind_Source near 0."),
        ],
    },
    # --------------------------------------------------------------------- Redis
    {
        "slug": "redis-diagnose-latency-spikes",
        "title": "Diagnose Redis latency spikes",
        "category": "redis",
        "severity": "incident",
        "summary": "Clients see intermittent latency. Separate host from Redis causes, hunt slow O(N) commands and big keys, check fork/persistence stalls, and mitigate with the latency monitor and THP off.",
        "owner": "marcus.chen@example.com",
        "tags": ["redis", "latency", "performance", "incident"],
        "related": ["redis-reduce-memory-eviction"],
        "steps": [
            ("Measure baseline latency to the server.",
             "redis-cli --latency -h prod-redis",
             "min/avg/max latency in ms; a high max points at intermittent stalls."),
            ("Sample intrinsic (host/kernel) latency.",
             "redis-cli --intrinsic-latency 5",
             "High intrinsic latency alone means the host, not Redis, is at fault."),
            ("Check the slowlog for expensive commands.",
             "redis-cli slowlog get 10",
             "Entries reveal O(N) commands like KEYS, SMEMBERS, or huge MGET."),
            ("Find big keys that can stall the event loop.",
             "redis-cli --bigkeys",
             "Reports the largest key per type; a huge collection blocks the loop."),
            ("Check memory pressure and fragmentation.",
             "redis-cli info stats | grep -E 'evicted_keys|keyspace_misses' ; redis-cli info memory | grep -E 'used_memory_human|mem_fragmentation_ratio'",
             "High evicted_keys or fragmentation ratio > 1.5 indicates memory-driven latency."),
            ("Check whether persistence forks are stalling.",
             "redis-cli info persistence | grep -E 'rdb_last_bgsave_status|aof_last_bgrewrite_status|latest_fork_usec'",
             "A large latest_fork_usec means fork() during save is stalling the process."),
            ("Attribute spikes with the latency monitor.",
             "redis-cli config set latency-monitor-threshold 100 ; sleep 60 ; redis-cli latency latest",
             "'latency latest' names the event (command, fork, expire-cycle)."),
            ("Mitigate a common fork stall by disabling THP.",
             "echo never > /sys/kernel/mm/transparent_hugepage/enabled",
             "Disabling transparent huge pages removes a frequent source of fork latency."),
        ],
    },
    {
        "slug": "redis-sentinel-failover",
        "title": "Fail over a Redis primary with Sentinel",
        "category": "redis",
        "severity": "incident",
        "summary": "The Redis primary is unreachable. Confirm Sentinel quorum, trigger a manual failover, verify the promoted replica accepts writes, and reattach the old primary as a replica.",
        "owner": "ana.ruiz@example.com",
        "tags": ["redis", "sentinel", "failover", "ha", "incident"],
        "related": ["redis-diagnose-latency-spikes"],
        "steps": [
            ("Check the current master as Sentinel sees it.",
             "redis-cli -p 26379 sentinel get-master-addr-by-name mymaster",
             "Returns the current master ip and port."),
            ("Verify Sentinels agree and quorum is met.",
             "redis-cli -p 26379 sentinel master mymaster | grep -E 'num-slaves|num-other-sentinels|quorum|flags'",
             "flags show master state and enough sentinels to meet quorum."),
            ("Confirm the master is actually unreachable.",
             "redis-cli -h current-master ping",
             "Times out or errors, justifying a failover."),
            ("Trigger a manual failover.",
             "redis-cli -p 26379 sentinel failover mymaster",
             "Returns OK; Sentinel promotes the best replica."),
            ("Watch the promotion complete.",
             "redis-cli -p 26379 sentinel get-master-addr-by-name mymaster",
             "Address changes to the newly promoted replica."),
            ("Verify the new master accepts writes.",
             "redis-cli -h new-master set failover_check ok ; redis-cli -h new-master get failover_check",
             "Returns OK then 'ok'."),
            ("Confirm replicas reattached to the new master.",
             "redis-cli -h new-master info replication | grep -E 'role:master|connected_slaves'",
             "role:master with the expected connected_slaves count."),
            ("Reattach the old master as a replica when it recovers.",
             "redis-cli -h old-master replicaof new-master 6379",
             "Old master syncs and rejoins as a replica."),
        ],
    },
    {
        "slug": "redis-reduce-memory-eviction",
        "title": "Reduce Redis memory usage and tune eviction",
        "category": "redis",
        "severity": "maintenance",
        "summary": "Redis is near maxmemory and evicting heavily. Find big/TTL-less keys, choose a sane eviction policy and maxmemory with headroom, enable active defrag, and persist the config.",
        "owner": "priya.nair@example.com",
        "tags": ["redis", "memory", "eviction", "maxmemory", "maintenance"],
        "related": ["redis-diagnose-latency-spikes"],
        "steps": [
            ("Inspect memory usage, limit, and fragmentation.",
             "redis-cli info memory | grep -E 'used_memory_human|maxmemory_human|mem_fragmentation_ratio'",
             "used_memory approaching maxmemory drives evictions."),
            ("Check the current eviction policy.",
             "redis-cli config get maxmemory-policy",
             "A 'noeviction' policy causes write errors; an lru/lfu policy evicts keys."),
            ("Find the biggest keys to target.",
             "redis-cli --bigkeys ; redis-cli --memkeys",
             "Largest keys by memory are identified for trimming or TTLs."),
            ("Sample keys that lack a TTL.",
             "redis-cli --scan --count 1000 | head -100 | xargs -n1 -I{} sh -c 'echo -n \"{} \"; redis-cli ttl {}'",
             "Keys returning -1 have no expiry and accumulate forever."),
            ("Switch to allkeys-lfu for better hit rates under pressure.",
             "redis-cli config set maxmemory-policy allkeys-lfu",
             "Eviction now targets least-frequently-used keys."),
            ("Set a maxmemory with headroom below RAM.",
             "redis-cli config set maxmemory 6gb",
             "used_memory now has room below the cap, reducing eviction churn."),
            ("Enable active defragmentation.",
             "redis-cli config set activedefrag yes",
             "Active defrag reclaims fragmented memory over time."),
            ("Persist the running config so it survives restart.",
             "redis-cli config rewrite",
             "The running config is written back to redis.conf."),
        ],
    },
    {
        "slug": "redis-cluster-reshard",
        "title": "Reshard a Redis Cluster onto a new node",
        "category": "redis",
        "severity": "maintenance",
        "summary": "Add capacity to a Redis Cluster: join a new master, migrate a slice of hash slots to it live, attach a replica, and rebalance so slots are evenly distributed.",
        "owner": "tom.obrien@example.com",
        "tags": ["redis", "cluster", "resharding", "slots", "maintenance"],
        "related": [],
        "steps": [
            ("Check cluster health and slot coverage.",
             "redis-cli --cluster check node1:6379",
             "All 16384 slots are covered and the cluster state is ok."),
            ("Review per-node slot distribution.",
             "redis-cli --cluster info node1:6379",
             "Slot counts per master reveal imbalance or a new empty node."),
            ("Add the new master node to the cluster.",
             "redis-cli --cluster add-node newnode:6379 node1:6379",
             "New node joins as a master with 0 slots."),
            ("Reshard a slice of slots onto the new node.",
             "redis-cli --cluster reshard node1:6379 --cluster-from all --cluster-to <newnode-id> --cluster-slots 4096 --cluster-yes",
             "4096 slots migrate to the new node with keys moved live."),
            ("Monitor the migration for stuck slots or errors.",
             "redis-cli --cluster check node1:6379 | grep -E 'migrating|importing|\\[ERR\\]'",
             "No slots stuck in migrating/importing and no [ERR] lines."),
            ("Attach a replica to the new master.",
             "redis-cli --cluster add-node newreplica:6379 node1:6379 --cluster-slave --cluster-master-id <newnode-id>",
             "Replica begins syncing from the new master."),
            ("Rebalance to even out remaining imbalance.",
             "redis-cli --cluster rebalance node1:6379 --cluster-use-empty-masters",
             "Slots are evened across masters."),
            ("Confirm the final state.",
             "redis-cli --cluster check node1:6379",
             "16384 slots covered, cluster state ok, balanced distribution."),
        ],
    },
    {
        "slug": "redis-recover-aof-corruption",
        "title": "Recover Redis from AOF corruption",
        "category": "redis",
        "severity": "incident",
        "summary": "Redis will not start because the append-only file is truncated or invalid. Back it up, repair to the last valid command with redis-check-aof, restart, and rewrite a clean base.",
        "owner": "yuki.tanaka@example.com",
        "tags": ["redis", "aof", "persistence", "recovery", "incident"],
        "related": ["redis-sentinel-failover"],
        "steps": [
            ("Confirm Redis is failing to load the AOF.",
             "sudo journalctl -u redis -n 50 | grep -iE 'bad file format|aof|truncated'",
             "Startup log shows an AOF parse or truncation error."),
            ("Back up the AOF directory before touching it.",
             "sudo cp -a /var/lib/redis/appendonlydir /var/lib/redis/appendonlydir.bak",
             "A full copy exists in case repair goes wrong."),
            ("Inspect the multi-part AOF manifest (Redis 7).",
             "cat /var/lib/redis/appendonlydir/appendonly.aof.manifest",
             "The manifest lists the base RDB and incremental AOF files."),
            ("Check the incremental AOF for corruption.",
             "redis-check-aof /var/lib/redis/appendonlydir/appendonly.aof.1.incr.aof",
             "Reports the offset where the file becomes invalid."),
            ("Repair by truncating to the last valid command.",
             "redis-check-aof --fix /var/lib/redis/appendonlydir/appendonly.aof.1.incr.aof",
             "Confirms truncation; the trailing partial command is removed."),
            ("Start Redis and verify it loads.",
             "sudo systemctl start redis ; redis-cli ping",
             "Returns PONG; the AOF now loads cleanly."),
            ("Validate the dataset size against expectations.",
             "redis-cli dbsize",
             "Key count is close to pre-incident levels, minus the truncated tail."),
            ("Rewrite a fresh, compact AOF base.",
             "redis-cli bgrewriteaof",
             "info persistence shows aof_last_bgrewrite_status:ok."),
        ],
    },
]


def seed_users(users_coll, user_ids: dict[str, ObjectId]) -> None:
    for user in USERS:
        _id = det_oid("user", user["email"])
        user_ids[user["email"]] = _id
        users_coll.replace_one({"_id": _id}, {"_id": _id, **user}, upsert=True)


def seed_runbooks(runbooks_coll, user_ids: dict[str, ObjectId]) -> None:
    for i, rb in enumerate(RUNBOOKS):
        _id = det_oid("runbook", rb["slug"])
        created = BASE + timedelta(days=i)
        doc = {
            "_id": _id,
            "title": rb["title"],
            "slug": rb["slug"],
            "category": rb["category"],
            "severity": rb["severity"],
            "summary": rb["summary"],
            "steps": build_steps(rb["steps"]),
            "tags": rb["tags"],
            "related_runbook_ids": [det_oid("runbook", s) for s in rb["related"]],
            "owner_id": user_ids[rb["owner"]],
            "created_at": created,
            "updated_at": created + timedelta(days=3, hours=i),
        }
        runbooks_coll.replace_one({"_id": _id}, doc, upsert=True)


def seed_execution_log(exec_coll) -> None:
    slugs = [rb["slug"] for rb in RUNBOOKS]
    emails = [u["email"] for u in USERS]
    # Weighted toward success, with some failed/aborted runs.
    outcomes = ["success", "success", "success", "failed", "aborted"]
    for i in range(30):
        # Step of 7 is coprime with 20, so all runbooks get covered.
        slug = slugs[(i * 7) % len(slugs)]
        email = emails[i % len(emails)]
        _id = det_oid("exec", str(i))
        doc = {
            "_id": _id,
            "runbook_id": det_oid("runbook", slug),
            "operator_id": det_oid("user", email),
            "ran_at": BASE + timedelta(days=40) - timedelta(hours=i * 5, minutes=(i * 13) % 60),
            "outcome": outcomes[i % len(outcomes)],
        }
        exec_coll.replace_one({"_id": _id}, doc, upsert=True)


def main() -> None:
    db = get_mongo()
    users_coll = db["users"]
    runbooks_coll = db["runbooks"]
    exec_coll = db["execution_log"]

    users_coll.create_index("email", unique=True)
    runbooks_coll.create_index("slug", unique=True)
    exec_coll.create_index([("runbook_id", ASCENDING), ("ran_at", ASCENDING)])

    user_ids: dict[str, ObjectId] = {}
    seed_users(users_coll, user_ids)
    seed_runbooks(runbooks_coll, user_ids)
    seed_execution_log(exec_coll)

    print(f"users:         {users_coll.count_documents({})}")
    print(f"runbooks:      {runbooks_coll.count_documents({})}")
    print(f"execution_log: {exec_coll.count_documents({})}")

    print("\n--- sample runbooks ---")
    for slug in ("pg-recover-replica-wal-lag", "redis-diagnose-latency-spikes"):
        doc = runbooks_coll.find_one({"slug": slug})
        print(json_util.dumps(doc, indent=2))


if __name__ == "__main__":
    main()
